
spring:
  data:
    mongodb:
      host: 47.116.11.247
      port: 27007
      database: HomeTeach
      username: normal
      password: Ww125696!
      authentication-database: admin
server:
  port: 82